version: "3.3"
services:
  zookeeper:
    image: debezium/zookeeper:2.0.0.Final
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    tmpfs: "/datalog"
    volumes:
      - /var/lib/zookeeper/data:/var/lib/zookeeper/data
      - /var/lib/zookeeper/log:/var/lib/zookeeper/log
      - /var/log/zookeeper:/var/log/zookeeper
    environment:
      KAFKA_HEAP_OPTS: '-Xms512M -Xmx512M'

  kafka:
    image: debezium/kafka:2.0.0.Final
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    ports:
      - 9200:9200
      - 9300:930
    environment:
      - discovery.type=single-node
  kafka-connect:
    image: debezium/connect:2.0.0.Final
    ports:
      - 8083:8083
    links:
      - kafka
      - elastic
      - zookeeper
      - postgres
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_source_connect_statuses
  postgres:
    image: postgres:11.7
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=demo
      - TZ=Asia/Ho_Chi_Minh
    ports:
      - 5435:5432
    command: [ "postgres", "-c", "wal_level=logical" ]